server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        url: jdbc:h2:mem:test
        driver-class-name: org.h2.Driver
        username: sa
        password: password
        type: org.apache.commons.dbcp2.BasicDataSource
      ds1:
        url: jdbc:h2:mem:test1
        driver-class-name: org.h2.Driver
        username: sa
        password: password
        type: org.apache.commons.dbcp2.BasicDataSource
      ds2:
        url: jdbc:h2:mem:test2
        driver-class-name: org.h2.Driver
        username: sa
        password: password
        type: org.apache.commons.dbcp2.BasicDataSource
    sharding:
      default-database-strategy:
        inline:
          sharding-column: sender_id
          algorithm-expression: ds$->{sender_id % 3}
      binding-tables: t_payment
      default-data-source-name: ds0
      tables:
        t_payment:
          actual-data-nodes: ds$->{0..2}.t_payment
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              worker:
                id: 123


  h2:
    console:
      enabled: true


